version: 0.0
os: windows
files:
  - source: \
    destination: C:\inetpub\wwwroot
hooks:
  BeforeInstall:
    - location: scripts\before_install.bat
      timeout: 900
  AfterInstall:
    - location: scripts\after_install.bat
      timeout: 300
  ApplicationStart:
    - location: scripts\start_server.bat
      timeout: 300
  ApplicationStop:
    - location: scripts\stop_server.bat
      timeout: 300
